export const API_ENDPOINTS = {
  SEND_OTP: "/auth/send-otp",
  VERIFY_OTP: "/auth/verify-otp",
  REGISTER: "/auth/register",
  REFRESH_TOKEN: "/auth/refresh-token",
  LOGOUT: "/auth/logout",
  PROFILE: "/auth/profile",
  ROLES: "/roles",
  BUSINESS_TYPES: "/business-types",
  CATEGORIES: "/categories",
  PRODUCTS: "/products",
  BRANDS: "/brands",
  BANNERS: "/banners",
  WISHLIST: "/wishlist",
  WISHLIST_TOGGLE: "/wishlist/toggle",
  RFQS: "/rfqs",
  RFQS_LATEST: "/rfqs/latest",
  RFQS_MY: "/rfqs/my",
  RFQS_SELLER_FEED: "/rfqs/seller/feed",
  RFQS_SELLER_QUOTATIONS: "/rfqs/seller/quotations",
  LOCATIONS_STATES: "/locations/states",
  LOCATIONS_CITIES: "/locations/cities",
  CHATS_CONVERSATIONS: "/chats/conversations",
  CHATS_UNREAD_SUMMARY: "/chats/unread-summary",
  CHATS_RFQ_CONVERSATIONS: "/chats/rfqs",
} as const;
